import {translate} from '@docusaurus/Translate';
import React, {useRef, useState} from 'react';
import Layout from '@theme/Layout';
import Link from '@docusaurus/Link';
import useBaseUrl, {useBaseUrlUtils} from '@docusaurus/useBaseUrl';
import useBrokenLinks from '@docusaurus/useBrokenLinks';
import siteLinks from '../../site-links';
import AppScreenshot from '../components/AppScreenshot';

const words = [
  {id:'field',thai:'นา',meaning:translate({id: "home.rice-field", message: "rice field"}),parts:['น','า'],note:translate({id: "home.start-with-n-then-hold-the-long-aa-sound-the-vowel-is-written-after-the-", message: "Start with n, then hold the long aa sound. The vowel is written after the consonant."}),x:57,y:63},
  {id:'crow',thai:'กา',meaning:translate({id: "home.crow", message: "crow"}),parts:['ก','า'],note:translate({id: "home.the-same-long-aa-vowel-with-a-different-consonant-one-small-change-makes", message: "The same long aa vowel, with a different consonant. One small change makes a new word."}),x:92,y:60},
  {id:'snake',thai:'งู',meaning:translate({id: "home.snake", message: "snake"}),parts:['ง','ู'],note:translate({id: "home.the-ng-sound-of-meets-a-long-oo-vowel-this-vowel-is-written-underneath-t", message: "The ng sound of ง meets a long oo vowel. This vowel is written underneath the consonant."}),x:77,y:89},
];
const shots = [
  {id:'discover',label:translate({id: "home.01-discover", message: "01 / Discover"}),title:translate({id: "home.a-picture-is-your-first-teacher", message: "A picture is your first teacher."}),text:translate({id: "home.explore-the-scene-before-you-try-to-read-it-tap-a-person-a-rice-field-or", message: "Explore the scene before you try to read it. Tap a person, a rice field or a snake to meet the Thai word."}),alt:translate({id: "home.read-thai-daily-discover-mode-showing-dao-and-din-in-a-rice-field-with-i", message: "Read Thai Daily Discover mode showing Dao and Din in a rice field with interactive object markers."})},
  {id:'talk',label:translate({id: "home.02-talk", message: "02 / Talk"}),title:translate({id: "home.one-small-sentence-at-a-time", message: "One small sentence at a time."}),text:translate({id: "home.big-thai-text-clearly-selectable-words-and-a-meaning-panel-right-beside-", message: "Big Thai text, clearly selectable words and a meaning panel right beside the story. Listen normally or slowly, then explore any word."}),alt:translate({id: "home.read-thai-daily-talk-mode-with-the-thai-word-audio-controls-and-an-expla", message: "Read Thai Daily Talk mode with a selected Thai word, audio controls and an explanation of its consonant and vowel."})},
  {id:'script',label:translate({id: "home.03-learn-thai-script", message: "03 / Learn Thai Script"}),title:translate({id: "home.every-letter-has-a-picture", message: "Every letter has a picture."}),text:translate({id: "home.consonants-are-grouped-by-class-vowels-have-their-own-section-and-famili", message: "Consonants are grouped by class, vowels have their own section, and familiar pictures follow each symbol into the script map."}),alt:translate({id: "home.read-thai-daily-learn-thai-script-showing-mid-class-consonants-and-an-il", message: "Read Thai Daily Learn Thai Script showing mid-class consonants and an illustrated consonant explanation."})},
];
const chapters = [
  {name:'Phrae',thai:'แพร่',image:'phrae.jpg',kind:translate({id: "home.start-here-free", message: "Start here · Free"}),description:translate({id: "home.meet-dao-and-din-rice-fields-breakfast-market-days-and-a-little-life-in-", message: "Meet Dao and Din. Rice fields, breakfast, market days and a little life in northern Thailand."})},
  {name:'Chiang Mai',thai:'เชียงใหม่',image:'chiang-mai.jpg',kind:translate({id: "home.continue-subscription", message: "Continue · Subscription"}),description:translate({id: "home.catch-a-bus-settle-into-a-guesthouse-order-khao-soi-and-explore-the-old-", message: "Catch a bus, settle into a guesthouse, order khao soi and explore the old city."})},
  {name:'Bangkok',thai:'กรุงเทพฯ',image:'bangkok.jpg',kind:translate({id: "home.explore-subscription", message: "Explore · Subscription"}),description:translate({id: "home.trains-river-boats-caf-stops-and-making-plans-in-the-big-city", message: "Trains, river boats, café stops and making plans in the big city."})},
  {name:'Hua Hin',thai:'หัวหิน',image:'hua-hin.jpg',kind:translate({id: "home.by-the-sea-subscription", message: "By the sea · Subscription"}),description:translate({id: "home.beach-colors-seafood-weather-bicycles-and-a-sweet-stop-at-the-night-mark", message: "Beach colors, seafood, weather, bicycles and a sweet stop at the night market."})},
];
const steps = [
  ['01',translate({id: "home.discover", message: "Discover"}),translate({id: "home.find-words-in-an-illustrated-scene-meaning-comes-first", message: "Find words in an illustrated scene. Meaning comes first."})],
  ['02',translate({id: "home.talk", message: "Talk"}),translate({id: "home.listen-and-explore-short-lines-with-familiar-words", message: "Listen and explore short lines with familiar words."})],
  ['03',translate({id: "home.build", message: "Build"}),translate({id: "home.put-consonants-and-vowels-together-in-written-order", message: "Put consonants and vowels together in written order."})],
  ['04',translate({id: "home.read", message: "Read"}),translate({id: "home.try-the-text-yourself-then-check-your-understanding", message: "Try the text yourself, then check your understanding."})],
  ['05',translate({id: "home.type", message: "Type"}),translate({id: "home.optional-keyboard-practice-see-the-word-and-find-its-letters", message: "Optional keyboard practice. See the word and find its letters."})],
];

function SceneDemo() {
  const [selected,setSelected] = useState(words[0]);
  return <div className="scene-demo">
    <div className="scene-art">
      <img src={useBaseUrl('/img/rice-field.jpg')} width="1536" height="1024" alt={translate({id: "home.dao-and-din-beside-a-rice-field-in-phrae-with-a-crow-on-the-fence-and-a-", message: "Dao and Din beside a rice field in Phrae, with a crow on the fence and a snake at the field edge."})} fetchPriority="high" />
      <div className="picture-hint"><span aria-hidden="true">✧</span> {translate({id: "home.tap-a-marker-meet-a-word", message: "Tap a marker. Meet a word."})}</div>
      {words.map(word=><button key={word.id} className={`scene-marker ${selected.id===word.id?'is-selected':''}`} style={{left:`${word.x}%`,top:`${word.y}%`}} aria-label={translate({id: 'home.explore-word', message: 'Explore {meaning}, {thai}'}, {meaning: word.meaning, thai: word.thai})} aria-pressed={selected.id===word.id} onClick={()=>setSelected(word)}><span aria-hidden="true">+</span></button>)}
    </div>
    <div className="word-reveal" aria-live="polite" aria-atomic="true">
      <div className="word-identity"><span className="eyebrow">{translate({id: "home.your-first-words", message: "Your first words"})}</span><span lang="th" className="demo-thai">{selected.thai}</span><span className="word-meaning">{selected.meaning}</span></div>
      <div className="word-explanation"><div className="demo-parts" aria-label={translate({id: "home.written-parts", message: "Written parts"})}>{selected.parts.map((part,i)=><React.Fragment key={part}>{i>0&&<span className="plus" aria-hidden="true">+</span>}<span lang="th" className="part">{part === "ู" ? "◌ู" : part}</span></React.Fragment>)}</div><p>{selected.note}</p></div>
    </div>
    <p className="demo-caption">{translate({id: "home.a-tiny-interactive-taste-of-the-app-try-the-crow-or-the-snake", message: "A tiny interactive taste of the app. Try the crow or the snake."})}</p>
  </div>;
}

function ScreenshotGallery() {
  const [index,setIndex] = useState(1);
  const dialog = useRef(null);
  const shot=shots[index];
  return <section id="screenshots" className="screenshots section-wrap" aria-labelledby="screenshots-title">
    <div className="section-heading"><div><span className="eyebrow">{translate({id: "home.inside-the-app", message: "Inside the app"})}</span><h2 id="screenshots-title">{translate({id: "home.a-little-help", message: "A little help."})}<br/>{translate({id: "home.right-where-you-need-it", message: "Right where you need it."})}</h2></div><p>{translate({id: "home.no-hunting-through-menus-for-the-letter-you-forgot-tap-a-word-or-symbol-", message: "No hunting through menus for the letter you forgot. Tap a word or symbol and keep the story in view."})}</p></div>
    <div className="screenshot-tabs" aria-label={translate({id: "home.choose-an-app-screenshot", message: "Choose an app screenshot"})}>{shots.map((item,i)=><button key={item.id} className={index===i?'selected':''} aria-pressed={index===i} onClick={()=>setIndex(i)}>{item.label}</button>)}</div>
    <figure className="app-window">
      <div className="window-bar" aria-hidden="true"><i/><i/><i/><span>Read Thai Daily · Mac</span></div>
      <button className="capture" aria-label={translate({id: 'home.enlarge-screenshot', message: 'Enlarge {name} screenshot'}, {name: shot.label})} onClick={()=>dialog.current.showModal()}><AppScreenshot name={shot.id} width="2880" height="1800" loading="lazy" alt={shot.alt}/><span className="enlarge-label">{translate({id: "home.view-larger", message: "View larger ↗"})}</span></button>
      <figcaption><div><strong>{shot.title}</strong><p>{shot.text}</p></div><span className="capture-label">{translate({id: "home.actual-app-screenshot", message: "Actual app screenshot"})}</span></figcaption>
    </figure>
    <dialog ref={dialog} className="screenshot-dialog" aria-label={translate({id: 'home.screenshot-dialog', message: '{name} app screenshot'}, {name: shot.label})}><button className="dialog-close" autoFocus onClick={()=>dialog.current.close()} aria-label={translate({id: "home.close-enlarged-screenshot", message: "Close enlarged screenshot"})}>{translate({id: "home.close", message: "Close ×"})}</button><AppScreenshot name={shot.id} alt={shot.alt}/><p>{shot.title}</p></dialog>
  </section>;
}

export default function Home() {
  const {withBaseUrl} = useBaseUrlUtils();
  const brokenLinks = useBrokenLinks();
  ['hero-title','how-it-works','how-title','screenshots','screenshots-title','script-title','chapters','chapters-title','pricing','pricing-title','closing-title'].forEach(id => brokenLinks.collectAnchor(id));
  return <Layout title={translate({id: "home.learn-to-read-thai-one-small-story-at-a-time", message: "Learn to read Thai, one small story at a time"})} description={translate({id: "home.start-from-zero-with-illustrated-thai-lessons-follow-dao-and-din-from-ph", message: "Start from zero with illustrated Thai lessons. Follow Dao and Din from Phrae to Chiang Mai, Bangkok and Hua Hin, on iPhone, iPad and Mac."})}>
    <main className="home">
      <section className="hero section-wrap" aria-labelledby="hero-title">
        <div className="hero-copy"><span className="eyebrow"><span className="sun" aria-hidden="true">☀</span> {translate({id: "home.a-little-thai-every-day", message: "A little Thai. Every day."})}</span><h1 id="hero-title">{translate({id: "home.from-your", message: "From your"})}<br/>{translate({id: "home.first-letter-to", message: "first letter to"})}<br/><em>{translate({id: "home.your-first-story", message: "your first story."})}</em></h1><p>{translate({id: "home.you-don-t-need-to-know-the-alphabet-to-begin-meet-dao-and-din-explore-th", message: "You don’t need to know the alphabet to begin. Meet Dao and Din, explore Thailand, and learn to read Thai—one small lesson at a time."})}</p><div className="hero-actions"><a className="cta" href={siteLinks.appStoreUrl}>{translate({id: "home.download-on-the-app-store", message: "Download on the App Store"})} <span aria-hidden="true">↗</span></a><a className="text-link" href="#screenshots">{translate({id: "home.take-a-look-inside", message: "Take a look inside"})} <span aria-hidden="true">↓</span></a></div><div className="device-note"><span className="status-dot"/> {translate({id: "home.for-iphone-ipad-mac", message: "For iPhone, iPad & Mac"})} <span className="note-divider">/</span> {translate({id: "home.the-phrae-chapter-is-free", message: "The Phrae chapter is free"})}</div></div>
        <SceneDemo/>
      </section>
      <div className="woven-divider" aria-hidden="true"/>
      <section className="intro-strip section-wrap" aria-label={translate({id: "home.app-overview", message: "App overview"})}><p><span className="mini-thai" lang="th">อ่าน</span> {translate({id: "home.a-new-way-into-the-thai-script", message: "A new way into the Thai script."})}</p><div><strong>{translate({id: "home.start-from-zero", message: "Start from zero"})}</strong><span>{translate({id: "home.no-alphabet-test-at-the-door", message: "No alphabet test at the door"})}</span></div><div><strong>{translate({id: "home.read-in-context", message: "Read in context"})}</strong><span>{translate({id: "home.pictures-people-everyday-life", message: "Pictures, people & everyday life"})}</span></div><div><strong>{translate({id: "home.four-teaching-languages", message: "Four teaching languages"})}</strong><span>English · Deutsch · Français · Español</span></div></section>
      <section id="how-it-works" className="how-section section-wrap" aria-labelledby="how-title"><div className="section-heading"><div><span className="eyebrow">{translate({id: "home.small-steps-a-real-journey", message: "Small steps. A real journey."})}</span><h2 id="how-title">{translate({id: "home.see-it-hear-it", message: "See it. Hear it."})}<br/><em>{translate({id: "home.then-read-it", message: "Then read it."})}</em></h2></div><p>{translate({id: "home.inspired-by-the-natural-method-understandable-scenes-short-texts-and-fam", message: "Inspired by the natural method: understandable scenes, short texts and familiar words returning in new situations. Add script explanations whenever you need them."})}</p></div><ol className="lesson-steps">{steps.map(([number,title,text])=><li key={number}><span className="step-number">{number}</span><h3>{title}{number==='05'&&<span className="optional">{translate({id: "home.optional", message: "optional"})}</span>}</h3><p>{text}</p></li>)}</ol><Link className="text-link" to="/guide/lessons">{translate({id: "home.walk-through-a-lesson", message: "Walk through a lesson"})} <span aria-hidden="true">↗</span></Link></section>
      <ScreenshotGallery/>
      <section className="script-feature" aria-labelledby="script-title"><div className="section-wrap script-layout"><div className="script-copy"><span className="eyebrow">{translate({id: "home.the-script-without-the-overwhelm", message: "The script, without the overwhelm"})}</span><h2 id="script-title">{translate({id: "home.a-letter", message: "A letter."})}<br/>{translate({id: "home.a-picture", message: "A picture."})}<br/><em>{translate({id: "home.a-way-to-remember", message: "A way to remember."})}</em></h2><p>{translate({id: "home.learn-consonants-by-class-and-explore-vowel-patterns-at-your-own-pace-tr", message: "Learn consonants by class and explore vowel patterns at your own pace. Traditional naming words, illustrated associations and plain-language sound explanations stay close at hand."})}</p><Link className="text-link" to="/guide/thai-script">{translate({id: "home.meet-the-thai-script", message: "Meet the Thai script"})} <span aria-hidden="true">↗</span></Link></div><div className="letter-display"><div className="letter-card"><img src={useBaseUrl('/img/chicken.jpg')} alt={translate({id: "home.illustrated-chicken-the-traditional-naming-picture-for", message: "Illustrated chicken, the traditional naming picture for ก"})} loading="lazy" width="512" height="512"/><span className="letter-glyph" lang="th">ก</span><div><span className="eyebrow">{translate({id: "home.mid-class-consonant", message: "Mid-class consonant"})}</span><h3 lang="th">ก ไก่</h3><p>{translate({id: "home.chicken-your-first-familiar-face", message: "Chicken. Your first familiar face."})}</p></div></div><div className="vowel-strip"><span lang="th">น</span><span className="plus">+</span><span lang="th">า</span><span className="plus">=</span><div><strong lang="th">นา</strong><span>{translate({id: "home.rice-field", message: "rice field"})}</span></div></div><span className="letter-footnote">{translate({id: "home.the-picture-stays-with-the-letter-in-the-app-s-script-map", message: "The picture stays with the letter in the app’s script map."})}</span></div></div></section>
      <section id="chapters" className="chapters section-wrap" aria-labelledby="chapters-title"><div className="section-heading"><div><span className="eyebrow">{translate({id: "home.from-phrae-into-the-world", message: "From Phrae into the world"})}</span><h2 id="chapters-title">{translate({id: "home.learn-the-words", message: "Learn the words."})}<br/><em>{translate({id: "home.live-the-little-stories", message: "Live the little stories."})}</em></h2></div><p>{translate({id: "home.dao-and-din-begin-at-home-in-phrae-each-chapter-brings-ten-lessons-local", message: "Dao and Din begin at home in Phrae. Each chapter brings ten lessons, local food and everyday language, building on the words you already know."})}</p></div><div className="chapter-grid">{chapters.map((chapter,index)=><Link key={chapter.name} className="chapter" to={`/guide/chapters#${['phrae','chiang-mai','bangkok','hua-hin'][index]}`}><div className="chapter-image"><img src={withBaseUrl(`/img/${chapter.image}`)} alt={translate({id: 'home.chapter-image', message: 'Dao and Din in {place}'}, {place: chapter.name})} width="900" height="600" loading="lazy"/><span className="chapter-number">0{index+1}</span></div><div className="chapter-meta"><span>{chapter.kind}</span><span lang="th">{chapter.thai}</span></div><h3>{chapter.name}<span aria-hidden="true">↗</span></h3><p>{chapter.description}</p></Link>)}</div><div className="chapter-note"><span aria-hidden="true">✧</span><p>{translate({id: "home.at-the-end-of-each-chapter-a-longer-reading-brings-familiar-vocabulary-t", message: "At the end of each chapter, a longer reading brings familiar vocabulary together into a story you can try for yourself."})}</p></div><div className="monthly-chapter"><span className="eyebrow">{translate({id: "home.the-journey-keeps-growing", message: "The journey keeps growing"})}</span><h3>{translate({id: "home.a-new-chapter-every-month", message: "A new chapter every month."})}</h3><p>{translate({id: "home.new-places-local-food-and-everyday-thai-built-on-the-words-you-already-k", message: "New places, local food and everyday Thai—built on the words you already know. Every new chapter is included in your subscription."})}</p></div></section>
      <section id="pricing" className="pricing-section section-wrap" aria-labelledby="pricing-title"><div className="pricing-intro"><span className="eyebrow">{translate({id: "home.start-in-phrae", message: "Start in Phrae"})}</span><h2 id="pricing-title">{translate({id: "home.your-first-chapter", message: "Your first chapter"})}<br/><em>{translate({id: "home.is-on-us", message: "is on us."})}</em></h2><p>{translate({id: "home.learn-thai-script-and-the-phrae-chapter-are-free-continue-the-journey-wi", message: "Learn Thai Script and the Phrae chapter are free. Continue the journey with one subscription for the premium chapters."})}</p><Link className="text-link" to="/guide/chapters">{translate({id: "home.what-s-included", message: "What’s included"})} <span aria-hidden="true">↗</span></Link></div><div className="pricing-options"><div className="free-plan"><span className="eyebrow">{translate({id: "home.phrae-learn-thai-script", message: "Phrae + Learn Thai Script"})}</span><h3>{translate({id: "home.free", message: "Free"})}</h3><p>{translate({id: "home.meet-the-characters-explore-the-script-start-reading", message: "Meet the characters. Explore the script. Start reading."})}</p></div><div className="paid-plan"><span className="eyebrow">{translate({id: "home.continue-the-journey", message: "Continue the journey"})}</span><div className="price"><strong>$2.99</strong><span>{translate({id: "home.usd-month", message: "USD / month"})}</span></div><p>{translate({id: "home.or-24-99-usd-per-year", message: "or $24.99 USD per year"})}</p><span className="plan-detail">Chiang Mai · Bangkok · Hua Hin</span></div><p className="price-note">{translate({id: "home.local-app-store-prices-may-vary-new-chapters-every-month-are-included-in", message: "Local App Store prices may vary. New chapters every month are included in both plans."})}</p></div></section>
      <section className="closing section-wrap" aria-labelledby="closing-title"><div><span className="eyebrow">{translate({id: "home.made-by-a-learner-for-learners", message: "Made by a learner, for learners"})}</span><h2 id="closing-title">{translate({id: "home.let-s-read-a-little", message: "Let’s read a little"})}<br/><em>{translate({id: "home.thai-today", message: "Thai today."})}</em></h2><p>{translate({id: "home.built-in-phrae-from-a-simple-wish-to-read-more-thai-a-new-chapter-every-", message: "Built in Phrae, from a simple wish to read more Thai. A new chapter every month brings another place to explore."})}</p><a className="cta" href={siteLinks.appStoreUrl}>{translate({id: "home.get-read-thai-daily", message: "Get Read Thai Daily"})} <span aria-hidden="true">↗</span></a></div><div className="closing-art"><img src={useBaseUrl('/img/farewell.jpg')} width="900" height="600" loading="lazy" alt={translate({id: "home.dao-and-din-wave-goodbye-to-a-friend-by-the-sea-in-hua-hin", message: "Dao and Din wave goodbye to a friend by the sea in Hua Hin."})}/></div></section>
    </main>
  </Layout>;
}
